# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Tickets"
  url = "https://ti.to/monki-gras/monki-gras-2025"
  weight = 10

[[main]]
  name = "Attend"
  weight = 20

  [[main]]
    parent = "Attend"
    name = "Schedule"
    pageref = "schedule"
    weight = 10

  [[main]]
    parent = "Attend"
    name = "Location"
    pageref = "attend/location"
    weight = 20

  [[main]]
    parent = "Attend"
    name = "Event FAQ"
    pageRef = "attend/faq"
    weight = 70

[[main]]
  name = "Program"
  weight = 40

  [[main]]
  parent = "Program"
  name = "Schedule"
  pageRef = "schedule"
  weight = 10

  [[main]]
  parent = "Program"
  name = "Speakers"
  pageRef = "speakers"
  weight = 20

  [[main]]
  parent = "Program"
  name = "Propose a Talk"
  url = "https://www.papercall.io/monkigras-2025"
  weight = 30

[[main]]
  name = "Sponsors"
  pageRef = "sponsors"
  weight = 60

[[main]]
  name = "Inclusion"
  pageRef = "inclusion"
  weight = 80

[[main]]
  name = "Conduct"
  pageRef = "conduct"
  weight = 90

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

